name: maplibre_webview
description: "WebView implementation for the maplibre package"
version: 0.3.4
repository: https://github.com/josxha/flutter-maplibre
issue_tracker: https://github.com/josxha/flutter-maplibre/issues
homepage: https://flutter-maplibre.pages.dev
documentation: https://flutter-maplibre.pages.dev/docs/index/

platforms: { android: , ios: , macos: , windows: }

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter: { sdk: flutter }
  flutter_inappwebview: ^6.1.5
  geobase: ^1.5.0
  maplibre_platform_interface: ^0.3.4

dev_dependencies:
  flutter_test: { sdk: flutter }
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
#      android:
#        dartPluginClass: MapLibrePlugin
#        dartFileName: 'src/maplibre_plugin.dart'
#      ios:
#        dartPluginClass: MapLibrePlugin
#        dartFileName: 'src/maplibre_plugin.dart'
      macos:
        dartPluginClass: MapLibrePlugin
        dartFileName: 'src/maplibre_plugin.dart'
      windows:
        dartPluginClass: MapLibrePlugin
        dartFileName: 'src/maplibre_plugin.dart'