name: maplibre_webview
description: "WebView implementation for the maplibre package"
version: 0.3.3+2
repository: https://github.com/josxha/flutter-maplibre
issue_tracker: https://github.com/josxha/flutter-maplibre/issues
homepage: https://flutter-maplibre.pages.dev
documentation: https://flutter-maplibre.pages.dev/docs/index/

platforms: { android: , ios: , macos: , windows: }

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter: { sdk: flutter }
  geobase: ^1.5.0
  maplibre_platform_interface: ^0.3.3+2

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
#      android:
#        pluginClass: MapLibrePlugin
      ios:
        pluginClass: MapLibrePlugin
      macos:
        pluginClass: MapLibrePlugin
      windows:
        pluginClass: MapLibrePlugin