name: maplibre_web
description: "iOS implementation for the maplibre package"
version: 0.3.3+2
repository: https://github.com/josxha/flutter-maplibre
issue_tracker: https://github.com/josxha/flutter-maplibre/issues
homepage: https://flutter-maplibre.pages.dev
documentation: https://flutter-maplibre.pages.dev/docs/index/

platforms: { web: }

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter: { sdk: flutter }
  flutter_web_plugins: { sdk: flutter }
  html: ^0.15.4
  maplibre_platform_interface: ^0.3.3+2
  pointer_interceptor: ^0.10.1+2
  web: ^1.0.0

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapLibrePlugin
        fileName: src/maplibre_plugin.dart